receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otelarrow:
    endpoint: "host.docker.internal:10000"
    arrow:
      disabled: false
      disable_downgrade: true
    tls:
      insecure: true
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelarrow]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelarrow]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelarrow]

  telemetry:
    logs:
      level: "debug"